spring:
 application:
  name: discovery-server 

server: 
 port: 9999 
  
 
eureka:
  instance:
    hostname: ec2-3-19-68-149.us-east-2.compute.amazonaws.com
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

